apiVersion: v1
kind: List
items:

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-config-node-a
   namespace: default
  data:
   config.properties: |-
    node_name=NodeA
    isolation=fence-method-config-node-a-fc-off
    power_management=fence-method-config-node-a-eaton-off, fence-method-config-node-a-eaton-on
    recovery=fence-method-config-node-a-fc-on

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-config-node-b
  data:
   config.properties: |-
    node_name=NodeB
    isolation=fence-method-config-node-b-fc-off
    power_management=fence-method-config-node-b-eaton-off fence-method-config-node-b-eaton-on
    recovery=fence-method-config-node-b-fc-on

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-fc-switch-brocade
   namespace: default
  data:
   template.properties: |-
          name=fc_switch_brocade
          agent_name=fence_brocade
          ipaddr=192.168.1.2
          password=brocade_password
          username=brocade_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-apc-pdu
   namespace: default
  data:
   template.properties: |-
          name=apc_pdu
          agent_name=fence_apc_snmp
          must_sucess=yes
          ipaddr=192.168.1.3
          password=apc_password
          username=apc_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-eaton-pdu
   namespace: default
  data:
   template.properties: |-
          name=eaton_pdu
          agent_name=fence_eaton_snmp
          must_sucess=yes
          ipaddr=192.168.1.4
          password=eaton_password
          username=eaton_admin
          snmp-priv-prot=AES
          snmp-priv-passwd=eaton_snmp_passwd
          snmp-sec-level=authPriv
          inet4-only=true

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-a-fc-off
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=1

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-a-fc-on
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=1

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-b-fc-off
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=2

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-b-fc-on
   namespace: default
  data:
   method.properties: |-
          template=fence-method-template-fc-switch-brocade
          plug=2

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-a-eaton-off
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=1
        action=off

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-a-eaton-on
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=1
        action=on

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-b-eaton-off
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=2
        action=off

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-config-node-b-eaton-on
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=2
        action=on